{% set name = "opentelemetry-exporter-gcp-monitoring" %}
{% set version = "1.7.0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e3a3bab8e78f953070a583468d9c1855b61f9d0c5f39b4f34b9b8fd671863c55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - google-cloud-monitoring >=2.0,<3.0
    - opentelemetry-api >=1.0,<2.0
    - opentelemetry-sdk >=1.0,<2.0
    - opentelemetry-resourcedetector-gcp >=1.5.0

test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/main/opentelemetry-exporter-gcp-monitoring
  summary: Google Cloud Monitoring exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
